import type { ThermalEvent } from "./types";

const history = (
  values: number[],
  baseline: number,
  startDay: number,
): ThermalEvent["history"] =>
  values.map((frp, index) => {
    const day = startDay + index;
    return {
      date: day > 31 ? `${String(day - 31).padStart(2, "0")} Sep` : `${String(day).padStart(2, "0")} Aug`,
      frp,
      baseline,
    };
  });

export const DEMO_EVENTS: ThermalEvent[] = [
  {
    id: "evt-west-041",
    shortId: "TW-2041",
    title: "West Coast Process Cluster",
    region: "Western industrial corridor",
    coordinates: [70.17, 22.35],
    classification: "Abnormal industrial heat",
    category: "industrial",
    confidence: 94,
    severity: "critical",
    status: "Elevated output",
    detectedAt: "01 Sep 2026 · 14:22 IST",
    sensor: "VIIRS NOAA-20",
    frp: 31.8,
    baselineFrp: 10.2,
    brightness: 367.4,
    persistence: 92,
    activeDays: 71,
    historyWindow: 90,
    nearestFacility: "Petroleum processing area",
    facilityDistance: "140 m",
    isNew: false,
    summary:
      "A stable, recurring source is emitting at more than three times its simulated historical baseline. Analyst review is recommended.",
    evidence: [
      {
        label: "Industrial context",
        value: "Inside mapped processing zone",
        impact: "positive",
        source: "OpenStreetMap demo cache",
      },
      {
        label: "Temporal recurrence",
        value: "71 active days / 90",
        impact: "positive",
        source: "ThermalWatch persistence engine",
      },
      {
        label: "FRP deviation",
        value: "+212% above baseline",
        impact: "positive",
        source: "NASA FIRMS demo cache",
      },
      {
        label: "Vegetation context",
        value: "3% within 1 km",
        impact: "negative",
        source: "Land-cover demo cache",
      },
    ],
    history: history([8.1, 10.4, 9.7, 12.2, 10.1, 11.4, 31.8], 10.2, 26),
  },
  {
    id: "evt-forest-117",
    shortId: "TW-2117",
    title: "Central Forest Sector",
    region: "Central India",
    coordinates: [80.96, 22.67],
    classification: "Vegetation fire",
    category: "vegetation",
    confidence: 91,
    severity: "high",
    status: "Expanding perimeter",
    detectedAt: "01 Sep 2026 · 13:48 IST",
    sensor: "VIIRS S-NPP",
    frp: 42.6,
    baselineFrp: 0,
    brightness: 372.1,
    persistence: 18,
    activeDays: 2,
    historyWindow: 90,
    nearestFacility: "No major facility mapped",
    facilityDistance: "18.4 km",
    isNew: true,
    summary:
      "A recent moving cluster overlaps dense vegetation and has no major mapped industrial infrastructure nearby.",
    evidence: [
      {
        label: "Forest coverage",
        value: "86% within 1 km",
        impact: "positive",
        source: "Land-cover demo cache",
      },
      {
        label: "Industrial proximity",
        value: "Nearest site 18.4 km",
        impact: "negative",
        source: "OpenStreetMap demo cache",
      },
      {
        label: "Cluster behavior",
        value: "Moving northeast",
        impact: "positive",
        source: "ThermalWatch persistence engine",
      },
      {
        label: "Cluster age",
        value: "First observed 2 days ago",
        impact: "positive",
        source: "NASA FIRMS demo cache",
      },
    ],
    history: history([0, 0, 0, 0, 0, 18.9, 42.6], 0, 26),
  },
  {
    id: "evt-crop-203",
    shortId: "TW-2203",
    title: "Northern Crop Belt",
    region: "Punjab agricultural zone",
    coordinates: [75.41, 30.74],
    classification: "Agricultural burning",
    category: "agricultural",
    confidence: 87,
    severity: "medium",
    status: "Seasonal pattern",
    detectedAt: "01 Sep 2026 · 12:56 IST",
    sensor: "VIIRS NOAA-21",
    frp: 17.3,
    baselineFrp: 1.4,
    brightness: 344.7,
    persistence: 12,
    activeDays: 3,
    historyWindow: 90,
    nearestFacility: "No industrial facility mapped",
    facilityDistance: "11.7 km",
    isNew: true,
    summary:
      "Short-lived, distributed detections overlap cropland and resemble a simulated seasonal field-burning pattern.",
    evidence: [
      {
        label: "Cropland coverage",
        value: "93% within 1 km",
        impact: "positive",
        source: "Land-cover demo cache",
      },
      {
        label: "Spatial stability",
        value: "Low — dispersed detections",
        impact: "positive",
        source: "ThermalWatch persistence engine",
      },
      {
        label: "Industrial proximity",
        value: "Nearest site 11.7 km",
        impact: "negative",
        source: "OpenStreetMap demo cache",
      },
    ],
    history: history([0, 0, 2.1, 0, 4.2, 13.5, 17.3], 1.4, 26),
  },
  {
    id: "evt-coast-084",
    shortId: "TW-2084",
    title: "Coastal Thermal Facility",
    region: "Eastern industrial coast",
    coordinates: [86.73, 21.04],
    classification: "Persistent industrial source",
    category: "industrial",
    confidence: 96,
    severity: "low",
    status: "Within baseline",
    detectedAt: "01 Sep 2026 · 11:34 IST",
    sensor: "VIIRS NOAA-20",
    frp: 8.7,
    baselineFrp: 8.2,
    brightness: 351.6,
    persistence: 95,
    activeDays: 78,
    historyWindow: 90,
    nearestFacility: "Mapped thermal power area",
    facilityDistance: "95 m",
    isNew: false,
    summary:
      "A highly persistent, spatially stable source remains inside its simulated operating baseline with no anomaly alert.",
    evidence: [
      {
        label: "Power context",
        value: "Inside mapped plant boundary",
        impact: "positive",
        source: "OpenStreetMap demo cache",
      },
      {
        label: "Temporal recurrence",
        value: "78 active days / 90",
        impact: "positive",
        source: "ThermalWatch persistence engine",
      },
      {
        label: "FRP deviation",
        value: "+6% above baseline",
        impact: "neutral",
        source: "NASA FIRMS demo cache",
      },
    ],
    history: history([7.8, 8.1, 8.5, 7.9, 8.3, 8.4, 8.7], 8.2, 26),
  },
  {
    id: "evt-unknown-017",
    shortId: "TW-U017",
    title: "Unmapped Persistent Cluster U-17",
    region: "Deccan plateau",
    coordinates: [77.48, 17.62],
    classification: "Unknown persistent source",
    category: "unknown",
    confidence: 82,
    severity: "high",
    status: "Investigation recommended",
    detectedAt: "01 Sep 2026 · 10:42 IST",
    sensor: "VIIRS S-NPP",
    frp: 12.1,
    baselineFrp: 9.4,
    brightness: 355.9,
    persistence: 88,
    activeDays: 66,
    historyWindow: 90,
    nearestFacility: "No matching heat source mapped",
    facilityDistance: "6.8 km",
    isNew: false,
    summary:
      "Repeated activity remains stable within 180 m, but no mapped refinery, plant, flare, or industrial polygon explains it.",
    evidence: [
      {
        label: "Temporal recurrence",
        value: "66 active days / 90",
        impact: "positive",
        source: "ThermalWatch persistence engine",
      },
      {
        label: "Spatial stability",
        value: "180 m centroid spread",
        impact: "positive",
        source: "ThermalWatch persistence engine",
      },
      {
        label: "Mapped context",
        value: "No expected source within 6.8 km",
        impact: "negative",
        source: "OpenStreetMap demo cache",
      },
      {
        label: "Land cover",
        value: "Built-up / bare terrain",
        impact: "neutral",
        source: "Land-cover demo cache",
      },
    ],
    history: history([8.4, 9.1, 9.6, 10.2, 9.8, 11.1, 12.1], 9.4, 26),
  },
];

export const CLASS_META = {
  industrial: { label: "Industrial", color: "#ff6b35" },
  vegetation: { label: "Vegetation", color: "#7ed957" },
  agricultural: { label: "Agricultural", color: "#f7bf4f" },
  unknown: { label: "Unknown", color: "#b28cff" },
} as const;
